### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by kumaranjeya** [04anubhavv/Skillshare-dl#1]
Hi,
I'm getting following error for recent courses (Using Python 3.9 and not effecting old courses):

E:\_Skillshare>python downloader.py
@K4ANUBHAV (。_。)
Enter class url:: https://www.skillshare.com/classes/Lighitng-for-Games-101-Fundamentals-of-Lighting-in-UE4-Part-2-Lighting-Blueprints-Office/825192496?via=search-layout-grid
Do you want to download subtitle (y/n): y
Do you want to download resources (y/n): y
ClassName : Lighitng for Games 101 : Fundamentals of Lighting in UE4 _ Part 2 + Lighting Blueprints Office
Traceback (most recent call last):
  File "E:\_Skillshare\downloader.py", line 26, in <module>
    dl.download_course_by_url(url, boolSubtitle, boolResources)
  File "E:\_Skillshare\skillshare.py", line 38, in download_course_by_url
    self.download_course_by_class_id(class_id, boolSubtitle, boolResources)
  File "E:\_Skillshare\skillshare.py", line 98, in download_course_by_class_id
    for u in data['_embedded']['units']['_embedded']['units']:
TypeError: list indices must be integers or slices, not str

Any ideas to resolve this issue? Thank you.

**Comment by C01Ntex** [comment]
Yes, new courses have changed. The script in this form will not work. I don't know if anyone is working on the problem.

**Comment by k4anubhav** [comment]
can you name some new courses which have this issue?

**Comment by jaum20** [comment]
@k4anubhav [This one](https://www.skillshare.com/classes/iPhone-Photography-How-to-Take-Pro-Lifestyle-Photos/1404933440?via=custom-lists) also have this same issue.

**Comment by jaum20** [comment]
Okay, I found a way. It's pretty easy since the json changed just a little bit. To make it work simply comment the line `for u in data['_embedded']['units']['_embedded']['units']:` and add a line `u=data` in `skillshare.py`

![image](https://user-images.githubusercontent.com/36702273/159355216-a43c7c9d-46bd-45bd-b1a0-2e8caaaca9cd.png)

**Comment by kumaranjeya** [comment]
@jaum20, Yes. Your code works. I'm able to download. Thank you.

**Comment by jaum20** [comment]
@kumaranjeya you are welcome. You will have to revert to the original code to download older courses tho
